# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SR
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lopencv_world452d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(SR.pri)
